HYDROPOWER = {
    'paid_up_capital': 'paid_up_capital',
    'reserve_&_surplus': 'reserves_and_surplus',
    'property,_plant_&_equipment_-_net_block_(net_fixed_assets)': 'net_fixed_assets',
    'investments': 'investments',
    'net_current_assets': 'net_current_assets',
    'operating_income': 'operating_margin',
    'operating_expenses': 'operating_margin',
    'net_profit': 'net_margin',
    'networth_per_share': 'book_value_per_share',
    'earnings_per_share_(eps_annualized_-rs.)': 'earning_per_share',
    'price_to_earning_ratio_(pe_ratio_-_times)': 'price_to_earnings_ratio',
    'return_on_assets_(roa_%)': 'return_on_assets',
    'return_on_equity_(roe_%)': 'return_on_equity',
    'total_current_liabilities': 'total_current_liabilities',
    'loans_&_long-term_liabilities': 'loans_&_long-term_liabilities',
    'operating_margin': 'operating_margin',
    'debt_to_equity_ratio': 'debt_to_equity_ratio',
    'dividend_yield': 'dividend_yield',
}
