# Generated by Django 4.2.2 on 2024-09-28 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True, verbose_name="Date")),
                (
                    "quarter",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Quarter"
                    ),
                ),
                (
                    "price",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Price"
                    ),
                ),
                (
                    "year",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Year"
                    ),
                ),
                (
                    "revenue",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Revenue"
                    ),
                ),
                (
                    "earning_per_share",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Earning Per Share EPS",
                    ),
                ),
                (
                    "dividends",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Dividends"
                    ),
                ),
                (
                    "price_to_earnings_ratio",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Price to earnings ratio",
                    ),
                ),
                (
                    "book_value_per_share",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Book value per share",
                    ),
                ),
                (
                    "debt_to_equity_ratio",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Debt to equity ratio",
                    ),
                ),
                (
                    "free_cash_flow",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Free cash flow",
                    ),
                ),
                (
                    "return_on_equity",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Return on equity",
                    ),
                ),
                (
                    "return_on_assets",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Return on assets",
                    ),
                ),
                (
                    "gross_margin",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Gross margin",
                    ),
                ),
                (
                    "operating_margin",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Operating margin",
                    ),
                ),
                (
                    "net_margin",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Net margin"
                    ),
                ),
                (
                    "current_ratio",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Current ratio",
                    ),
                ),
                (
                    "quick_ratio",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Quick ratio",
                    ),
                ),
                (
                    "earnings_growth_rate",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Earnings growth rate",
                    ),
                ),
                (
                    "dividend_yield",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Dividend yield",
                    ),
                ),
                (
                    "price_to_sales_ratio",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Price to sales ratio",
                    ),
                ),
                (
                    "paid_up_capital",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Paid up Capital",
                    ),
                ),
                (
                    "reserves_and_surplus",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Reserves And Surplus",
                    ),
                ),
                (
                    "deposit",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Deposit"
                    ),
                ),
                (
                    "non_performing_loan",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Non Performing Loan",
                    ),
                ),
                (
                    "price_earning_to_growth",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Price Earning To Growth PEG",
                    ),
                ),
                (
                    "investments",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Investments",
                    ),
                ),
                (
                    "net_current_assets",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Net Current Assets",
                    ),
                ),
                (
                    "net_fixed_assets",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Net Fixed Assets",
                    ),
                ),
                (
                    "symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.symbol",
                        verbose_name="Symbol",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Financial Data",
                "db_table": "financial_data",
            },
        ),
    ]
