# Generated by Django 4.2.2 on 2023-06-13 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundamental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialdata',
            name='net_fixed_assets',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Net Fixed Assets'),
        ),
    ]
