# Generated by Django 4.2.1 on 2023-06-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default/image.png', upload_to='user', verbose_name='image'),
        ),
    ]
